spring:
  datasource:
    jdbc-url: jdbc:mysql://localhost:3306/elk?useUnicode=true&characterEncoding=utf8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root

  liquibase:
   change-log: classpath:/schema/changelog-master.xml

server:
  port: 8889
