spring:
  datasource:
    jdbc-url: jdbc:log4jdbc:mysql://localhost:3306/elk?useUnicode=true&characterEncoding=utf8&useSSL=false
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    username: root
    password: root
  liquibase:
    change-log: classpath:/schema/changelog-master.xml

server:
  port: 8889

logging:
  level:
    root: ERROR
    com.doum: DEBUG